CREATE TABLE IF NOT EXISTS champion
(
    id           INTEGER PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    gender       VARCHAR(20),
    position     VARCHAR(50),
    species      VARCHAR(100),
    resource     VARCHAR(50),
    range_type   VARCHAR(20),
    region       VARCHAR(100),
    release_year INTEGER
);

INSERT INTO champion (id, name, gender, position, species, resource, range_type, region, release_year)
VALUES (1, 'Aatrox', 'Male', 'Top', 'Darkin', 'Manaless', 'Melee', 'Runeterra, Shurima', 2013),
       (2, 'Ahri', 'Female', 'Middle', 'Vastayan', 'Mana', 'Ranged', 'Ionia', 2011),
       (3, 'Akali', 'Female', 'Middle', 'Human', 'Energy', 'Melee', 'Ionia', 2010),
       (4, 'Akshan', 'Male', 'Middle', 'Human', 'Mana', 'Ranged', 'Shurima', 2021),
       (5, 'Alistar', 'Male', 'Support', 'Minotaur', 'Mana', 'Melee', 'Noxus, Runeterra', 2009),
       (6, 'Amumu', 'Male', 'Jungle', 'Undead, Yordle', 'Mana', 'Melee', 'Shurima', 2009),
       (7, 'Ambessa', 'Female', 'Top', 'Human', 'Energy', 'Melee', 'Noxus, Piltover', 2024),
       (8, 'Anivia', 'Female', 'Middle', 'God, Spirit', 'Mana', 'Ranged', 'Freljord', 2009),
       (9, 'Annie', 'Female', 'Middle', 'Human, Magicborn', 'Mana', 'Ranged', 'Noxus, Runeterra', 2009),
       (10, 'Aphelios', 'Male', 'Bottom', 'Human, Spiritualist', 'Mana', 'Ranged', 'Targon', 2019),
       (11, 'Ashe', 'Female', 'Bottom', 'Human, Iceborn', 'Mana', 'Ranged', 'Freljord', 2009),
       (12, 'Aurelion Sol', 'Male', 'Middle', 'Celestial, Dragon', 'Mana', 'Ranged', 'Runeterra, Targon', 2016),
       (13, 'Aurora', 'Female', 'Middle', 'Vastayan', 'Mana', 'Ranged', 'Freljord', 2024),
       (14, 'Azir', 'Male', 'Middle', 'God-Warrior', 'Mana', 'Ranged', 'Shurima', 2014),
       (15, 'Bard', 'Male', 'Support', 'Celestial', 'Mana', 'Ranged', 'Runeterra', 2015),
       (16, 'BelVeth', 'Female', 'Jungle', 'Void-Being', 'Manaless', 'Melee', 'Void', 2022),
       (17, 'Blitzcrank', 'Other', 'Support', 'Golem', 'Mana', 'Melee', 'Zaun', 2009),
       (18, 'Brand', 'Male', 'Support', 'Human, Magically Altered', 'Mana', 'Ranged', 'Freljord, Runeterra', 2011),
       (19, 'Braum', 'Male', 'Support', 'Human, Iceborn', 'Mana', 'Melee', 'Frejord', 2014),
       (20, 'Briar', 'Female', 'Jungle', 'Golem', 'Health costs', 'Melee', 'Noxus', 2023),
       (21, 'Caitlyn', 'Female', 'Bottom', 'Human', 'Mana', 'Ranged', 'Piltover', 2011),
       (22, 'Camille', 'Female', 'Top', 'Cyborg, Human', 'Mana', 'Melee', 'Piltover', 2016),
       (23, 'Cassiopea', 'Female', 'Middle, Top', 'Human, Magically Altered', 'Mana', 'Ranged', 'Noxus, Shurima', 2010),
       (24, 'Chogath', 'Male', 'Top', 'Void-Being', 'Mana', 'Melee', 'Void', 2009),
       (25, 'Corki', 'Male', 'Bottom', 'Yordle', 'Mana', 'Ranged', 'Bandle City, Piltover', 2009),
       (26, 'Darius', 'Male', 'Top', 'Human', 'Mana', 'Melee', 'Noxus', 2012),
       (27, 'Diana', 'Female', 'Jungle, Middle', 'Aspect, Human', 'Mana', 'Melee', 'Targon', 2012),
       (28, 'Draven', 'Male', 'Bottom', 'Human', 'Mana', 'Ranged', 'Noxus', 2012),
       (29, 'Dr. Mundo', 'Male', 'Jungle, Top', 'Chemically Altered, Human', 'Health costs', 'Melee', 'Zaun', 2009),
       (30, 'Ekko', 'Male', 'Jungle, Middle,', 'Human', 'Mana', 'Melee', 'Zaun', 2015),
       (31, 'Elise', 'Female', 'Jungle, Support', 'Human, Magically Altered', 'Mana', 'Melee, Ranged',
        'Noxus, Shadow Isles', 2012),
       (32, 'Evelynn', 'Female', 'Jungle', 'Deamon, Spirit', 'Mana', 'Melee', 'Runeterra', 2009),
       (33, 'Ezrael', 'Male', 'Bottom', 'Human, Magicborn', 'Mana', 'Ranged', 'Piltover', 2010),
       (34, 'Fiddlesticks', 'Other', 'Jungle', 'Demon, Spirit', 'Mana', 'Ranged', 'Runeterra', 2009),
       (35, 'Fiora', 'Female', 'Top', 'Human', 'Mana', 'Melee', 'Demacia', 2012),
       (36, 'Fizz', 'Male', 'Middle', 'Yordle', 'Mana', 'Melee', 'Bilgewater', 2011),
       (37, 'Miss Fortune', 'Female', 'Bottom', 'Human', 'Mana', 'Ranged', 'Bilgewater', 2010),
       (38, 'Twisted Fate', 'Male', 'Middle', ' Human, Magicborn', 'Mana', 'Ranged', 'Bilgewater', 2009),
       (39, 'Galio', 'Male', 'Middle', 'Golem', 'Mana', 'Melee', 'Demacia', 2010),
       (40, 'Gangplank', 'Male', 'Top', 'Human', 'Mana', 'Melee', 'Bilgewater', 2009),
       (41, 'Garen', 'Male', 'Top', 'Human', 'Manaless', 'Melee', 'Demacia', 2010),
       (42, 'Gnar', 'Male', 'Top', 'Yordle', 'Rage', 'Melee, Ranged', 'Freljord', 2014),
       (43, 'Gragas', 'Male', 'Jungle, Top', 'Human, Iceborn', 'Mana', 'Melee', 'Freljord', 2010),
       (44, 'Graves', 'Male', 'Jungle', 'Human', 'Mana', 'Ranged', 'Bilgewater', 2011),
       (45, 'Gwen', 'Female', 'Jungle, Top', 'Human, Magically Altered', 'Mana', 'Melee', 'Camavor, Shadow Isles',
        2021),
       (46, 'Renata Glasc', 'Female', 'Support', 'Chemically Altered Human', 'Mana', 'Ranged', 'Zaun', 2022),
       (47, 'Hecarim', 'Male', 'Jungle', 'Undead', 'Mana', 'Melee', 'Camavor, Shadow Isles', 2012),
       (48, 'Heimerdinger', 'Male', 'Middle, Top', 'Yordle', 'Mana', 'Rnaged', 'Piltover', 2009),
       (49, 'Hwei', 'Male', 'Middle', 'Human, Magicborn', 'Mana', 'Ranged', 'Ionia', 2023),
       (50, 'Illaoi', 'Female', 'Top', 'Human, Spiritualist', 'Mana', 'Melee', 'Ionia', 2010),
       (51, 'Irelia', 'Female', 'Top', 'Human, Spiritualist', 'Mana', 'Melee', 'Ionia', 2010),
       (52, 'Ivern', 'Male', 'Jungle', 'Human, Magically Altered', 'Mana', 'Ranged', 'Freljord, Ionia', 2016),
       (53, 'Janna', 'Female', 'Support', 'God, Spririt', 'Mana', 'Ranged', 'Shurima, Zaun', 2009),
       (54, 'Jarvan', 'Male', 'Jungle', 'Human', 'Mana', 'Melee', 'Demacia', 2011),
       (55, 'Jax', 'Male', 'Jungle, Top', 'Unknown', 'Mana', 'Melee', 'Icathia, Runeterra, Shurima', 2009),
       (56, 'Jayce', 'Male', 'Jungle, Top', ' Human', 'Mana', 'Melee, Ranged', 'Piltover', 2012),
       (57, 'Jhin', 'Male', 'Bottom', 'Human, Spiritualist', 'Mana', 'Ranged', 'Ionia', 2016),
       (58, 'Jinx', 'Female', 'Bottom', 'Chemically Altered, Human', 'Mana', 'Ranged', 'Zaun', 2013),
       (59, 'Ksante', 'Male', 'Top', 'Human', 'Mana', 'Melee', 'Shurima', 2022),
       (60, 'Kaisa', 'Female', 'Bottom', 'Human, Void-Being', 'Mana', 'Ranged', 'Shurima, Void', 2018),
       (61, 'Kalista', 'Female', 'Bottom', 'Undead', 'Mana', 'Ranged', 'Camover, Shadow Isles', 2014),
       (62, 'Karma', 'Female', 'Support', 'Human, Spiritualist', 'Mana', 'Ranged', 'Ionia', 2011),
       (63, 'Karthus', 'Male', 'Jungle', 'Undead', 'Mana', 'Ranged', 'Noxus, Shadow Isles', 2009),
       (64, 'Kassadin', 'Male', 'Middle', 'Human, Void-Being', 'Mana', 'Melee', 'Shurima, Void', 2009),
       (65, 'Katarina', 'Female', 'Middle', 'Human', 'Manaless', 'Melee', 'Noxus', 2009),
       (66, 'Kayle', 'Female', 'Top', 'Aspect, Human, Magically Altered', 'Mana', 'Melee, Ranged', 'Demacia, Targon',
        2009),
       (67, 'Kayn', 'Male', 'Jungle', 'Darkin, Human, Magically Altered', 'Mana', 'Melee',
        'Ionia, Noxus, Runeterra, Shurima', 2017),
       (68, 'Kennen', 'Male', 'Middle, Top', 'Yordle', 'Energy', 'Ranged', 'Ionia', 2010),
       (69, 'Khazix', 'Male', 'Jungle', 'Void-Being', 'Mana', 'Melee', 'Void', 2012),
       (70, 'Kindred', 'Other', 'Jungle', 'Void-Being', 'Mana', 'Ranged', 'Runeterra', 2015),
       (71, 'Kled', 'Male', 'Top', 'Yordle', 'Courage', 'Melee', 'Noxus', 2016),
       (72, 'Kogmaw', 'Male', 'Bottom', 'Void-Being', 'Mana', 'Ranged', 'Void', 2015),
       (73, 'Tahm Kench', 'Male', 'Support, Top', 'Demon, Spirit', 'Mana', 'Melee', 'Bilgewater, Runeterra', 2015),
       (74, 'LeBlanc', 'Female', 'Middle', 'Human, Magically Altered', 'Mana', 'Ranged', 'Noxus', 2010),
       (75, 'Lee Sin', 'Male', 'Jungle', 'Human, Spiritualist', 'Energy', 'Melee', 'Ionia', 2011),
       (76, 'Leona', 'Female', 'Support', 'Aspect, Human', 'Mana', 'Melee', 'Targon', 2011),
       (77, 'Lillia', 'Female', 'Jungle', 'Spirit ', 'Mana', 'Melee', 'Ionia', 2020),
       (78, 'Lissandra', 'Female', 'Middle', 'Human, Iceborn', 'Mana', 'Ranged', 'Freljord', 2013),
       (79, 'Lucian', 'Male', 'Bottom', 'Human', 'Mana', 'Ranged', 'Demacia, Shadow Isles', 2013),
       (80, 'Lulu', 'Female', 'Support', 'Yordle', 'Mana', 'Ranged', 'Bandle City', 2012),
       (81, 'Lux', 'Female', 'Middle, Support', 'Human, Magicborn', 'Mana', 'Ranged', 'Demacia', 2010),
       (82, 'Malphite', 'Male', 'Top', 'Golem', 'Mana', 'Melee', 'Ixtal, Shurima', 2009),
       (83, 'Malzahr', 'Middle', 'Middle', 'Human, Void-Being', 'Mana', 'Ranged', 'Shurima, Void', 2010),
       (84, 'Maokai', 'Male', 'Support', 'Spirit', 'Mana', 'Melee', 'Shadow Isles', 2011),
       (85, 'Master Yi', 'Male', 'Jungle', 'Human, Spiritualist', 'Mana', 'Melee', 'Ionia', 2009),
       (86, 'Mel', 'Female', 'Middle', 'Human, Magically Altered', 'Mana', 'Ranged', 'Noxus, Piltover', 2025),
       (87, 'Milio', 'Male', 'Support', 'Human, Magicborn', 'Mana', 'Ranged', 'Ixtal', 2023),
       (88, 'Mordekaiser', 'Male', 'Top', 'Revenant', 'Shield', 'Melee', 'Noxus, Shadow Isles', 2010),
       (89, 'Morgana', 'Female', 'Middle, Support', 'Aspect, Human, Magically Altered', 'Mana', 'Ranged',
        'Demacia, Targon', 2009),
       (90, 'Naafri', 'Female', 'Jungle, Middle', 'Darkin, Dog', 'Mana', 'Melee', 'Shurima', 2023),
       (91, 'Nami', 'Female', 'Support', 'Vastayan', 'Mana', 'Ranged', 'Bilgewater, Runeterra', 2012),
       (92, 'Nasus', 'Male', 'Top', 'God-Warrior', 'Mana', 'Melee', 'Shurima', 2009),
       (93, 'Nautilus', 'Male', 'Support', 'Revenant', 'Mana', 'Melee', 'Bilgewater', 2012),
       (94, 'Neeko', 'Female', 'Support', 'Vastayan', 'Mana', 'Ranged', 'Ixtal', 2018),
       (95, 'Nidalee', 'Female', 'Jungle', 'Human, Spiritualist', 'Mana', 'Melee, Ranged', 'Ixtal', 2009),
       (96, 'Nilah', 'Female', 'Bottom', 'Human, Magically Altered', 'Mana', 'Melee', 'Bilgewater', 2022),
       (97, 'Nocturne', 'Male', 'Jungle', 'Demon, Spirit', 'Mana', 'Melee', 'Runeterra', 2011),
       (98, 'Nunu & Willump', 'Male', 'Jungle', 'Human, Yeti', 'Mana', 'Melee', 'Freljord', 2009),
       (99, 'Olaf', 'Male', 'Top', 'Human, Iceborn', 'Mana', 'Melee', 'Freljord', 2010),
       (100, 'Orianna', 'Female', 'Middle', 'Golem', 'Mana', 'Ranged', 'Piltover', 2011),
       (101, 'Ornn', 'Male', 'Top', 'God, Spirit', 'Mana', 'Melee', 'Freljord', 2017),
       (102, 'Pantheon', 'Male', 'Jungle, Support, Top', 'Aspect, Human', 'Mana', 'Melee', 'Targon', 2010),
       (103, 'Poppy', 'Female', 'Support, Top', 'Yordle', 'Mana', 'Melee', 'Demacia', 2010),
       (104, 'Pyke', 'Male', 'Support', 'Revenant', 'Mana', 'Melee', 'Bilgewater', 2018),
       (105, 'Qijana', 'Female', 'Jungle, Middle', 'Human, Magicborn', 'Mana', 'Melee', 'Ixtal', 2019),
       (106, 'Quinn', 'Female', 'Top', 'Human', 'Mana', 'Ranged', 'Demacia', 2013),
       (107, 'Rakan', 'Male', 'Support', 'Vastayan', 'Mana', 'Melee', 'Ionia', 2017),
       (108, 'Rammus', 'Male', 'Jungle', 'Unknown', 'Mana', 'Melee', 'Shurima', 2009),
       (109, 'Reksai', 'Female', 'Jungle', 'Void-Being', 'Rage', 'Melee', 'Shurima, Void', 2014),
       (110, 'Rell', 'Female', 'Support', 'Human, Magically Altered, Magicborn', 'Mana', 'Melee', 'Noxus', 2020),
       (111, 'Renekton', 'Male', 'Top', 'God-Warrior', 'Fury', 'Melee', 'Shurima', 2011),
       (112, 'Rengar', 'Male', 'Jungle', 'Vastayan', 'Ferocity', 'Melee', 'Ixtal, Shurima', 2012),
       (113, 'Riven', 'Female', 'Top', 'Human', 'Manaless', 'Melee', 'Ionia, Noxus', 2011),
       (114, 'Rumble', 'Male', 'Top', 'Yordle', 'Heat', 'Melee', 'Bandle City', 2011),
       (115, 'Ryze', 'Male', 'Middle', 'Human, Magically Altered', 'Mana', 'Ranged', 'Runeterra', 2009),
       (116, 'Samira', 'Female', 'Bottom', 'Human', 'Mana', 'Ranged', 'Noxus, Shurima', 2020),
       (117, 'Sejuani', 'Female', 'Jungle', 'Human, Iceborn', 'Mana', 'Ranged', 'Freljord', 2012),
       (118, 'Senna', 'Female', 'Support', 'Human, Undead', 'Mana', 'Ranged', 'Shadow Isles', 2019),
       (119, 'Seraphine', 'Female', 'Support', 'Human, Magicborn', 'Mana', 'Ranged', 'Piltover, Zaun', 2020),
       (120, 'Sett', 'Male', 'Top', 'Human, Vastayan', 'Grit', 'Melee', 'Ionia', 2020),
       (121, 'Shaco', 'Male', 'Jungle, Support', 'Spirit', 'Mana', 'Melee', 'Runeterra', 2009),
       (122, 'Shen', 'Male', 'Support, Top', 'Human, Spiritualist', 'Energy', 'Melee', 'Ionia', 2010),
       (123, 'Shyvana', 'Female', 'Jungle', 'Dragon, Magically Altered', 'Fury', 'Melee', 'Demacia', 2011),
       (124, 'Singed', 'Male', 'Top', 'Chemically Altered, Human', 'Mana', 'Melee', 'Piltover, Zaun', 2009),
       (125, 'Sion', 'Male', 'Top', 'Revenant', 'Mana', 'Melee', 'Noxus', 2009),
       (126, 'Sivir', 'Female', 'Bottom', 'Human', 'Mana', 'Ranged', 'Shurima', 2009),
       (127, 'Skarner', 'Male', 'Jungle', 'Brackern', 'Mana', 'Melee', 'Ixtal', 2011),
       (128, 'Smolder', 'Male', 'Bottom', 'Dragon', 'Mana', 'Ranged', 'Camavor, Noxus', 2024),
       (129, 'Sona', 'Female', 'Support', 'Human, Magicborn', 'Mana', 'Ranged', 'Demacia, Ionia', 2010),
       (130, 'Soraka', 'Female', 'Support', 'Celestial', 'Mana', 'Ranged', 'Ionia, Targon', 2009),
       (131, 'Swain', 'Male', 'Support', 'Human, Magically Altered', 'Mana', 'Ranged', 'Noxus', 2010),
       (132, 'Sylas', 'Male', 'Jungle, Middle', 'Human, Magicborn', 'Mana', 'Melee', 'Demacia, Freljord', 2019),
       (133, 'Syndra', 'Female', 'Middle', 'Human, Magicborn', 'Mana', 'Ranged', 'Ionia', 2012),
       (134, 'Taliyah', 'Female', 'Middle', 'Human, Magicborn', 'Mana', 'Ranged', 'Shurima', 2016),
       (135, 'Talon', 'Male', 'Jungle, Middle', 'Human', 'Mana', 'Melee', 'Noxus', 2011),
       (136, 'Taric', 'Male', 'Support', 'Aspect, Human', 'Mana', 'Melee', 'Demacia, Targon', 2009),
       (137, 'Teemo', 'Male', 'Top', 'Yordle', 'Mana', 'Ranged', 'Bandle City', 2009),
       (138, 'Thresh', 'Male', 'Support', 'Undead', 'Mana', 'Ranged', 'Shadow Isles', 2013),
       (139, 'Tristana', 'Female', 'Bottom', 'Yordle', 'Mana', 'Ranged', 'Bandle City', 2009),
       (140, 'Trundle', 'Male', 'Jungle, Top', 'Iceborn, Troll', 'Mana', 'Melee', 'Freljord', 2010),
       (141, 'Tryndamere', 'Male', 'Top', 'Human, Magicalla Altered', 'Fury', 'Melee', 'Freljord', 2009),
       (142, 'Twitch', 'Male', 'Bottom', 'Chemically Altered, Rat', 'Mana', 'Ranged', 'Zaun', 2009),
       (143, 'Udyr', 'Male', 'Jungle', 'Human, Spiritualist', 'Mana', 'Melee', 'Freljord, Ionia', 2009),
       (144, 'Urgot', 'Male', 'Top', 'Chemically Altered, Cyborg, Human', 'Mana', 'Ranged', 'Noxus, Zaun', 2010),
       (145, 'Varus', 'Male', 'Bottom', 'Darkin, Human', 'Mana', 'Ranged', 'Ionia, Runeterra, Shurima', 2012),
       (146, 'Vayne', 'Female', 'Bottom, Top', 'Human', 'Mana', 'Ranged', 'Demacia', 2011),
       (147, 'Veigar', 'Male', 'Middle', 'Yordle', 'Mana', 'Ranged', 'Bandle City, Runeterra, Shadow Isles', 2009),
       (148, 'Velkoz', 'Male', 'Middle, Support', 'Void-Being', 'Mana', 'Ranged', 'Void', 2014),
       (149, 'Vex', 'Female', 'Middle', 'Yordle', 'Mana', 'Ranged', 'Bandle City, Shadow Isles', 2021),
       (150, 'Vi', 'Female', 'Jungle', 'Human', 'Mana', 'Melee', 'Piltover, Zaun', 2012),
       (151, 'Viego', 'Male', 'Jungle', 'Undead', 'Manaless', 'Melee', 'Camavor, Shadow Isles', 2021),
       (152, 'Victor', 'Male', 'Middle', 'Cyborg, Human', 'Mana', 'Ranged', 'Piltover, Zaun', 2011),
       (153, 'Vladimir', 'Male', 'Middle, Top', 'Human, Magically Altered', 'Bloodthirst', 'Ranged',
        'Camavor, Noxus, Shadow Isles', 2010),
       (154, 'Volibear', 'Male', 'Jungle, Top', 'God, Spirit', 'Mana', 'Melee', 'Freljord', 2011),
       (155, 'Warwick', 'Male', 'Jungle', 'Chemically Altered, Cyborg, Human', 'Mane', 'Melee', 'Zaun', 2009),
       (156, 'Wukong', 'Male', 'Jungle', 'Vastayan', 'Mana', 'Melee', 'Ionia', 2011),
       (157, 'Xayah', 'Female', 'Bottom', 'Vastayan', 'Mana', 'Ranged', 'Ionia', 2017),
       (158, 'Xerath', 'Male', 'Middle, Support', 'Baccai', 'Mana', 'Ranged', 'Shurima', 2011),
       (159, 'Xin Zhao', 'Male', 'Jungle', 'Human', 'Mana', 'Melee', 'Demacia, Ionia, Noxus', 2010),
       (160, 'Yasuo', 'Male', 'Middle, Top', 'Human, Magicborn', 'Flow', 'Melee', 'Ionia', 2013),
       (161, 'Yone', 'Male', 'Middle, Top', 'Human, Magically Altered', 'Manaless', 'Melee', 'Ionia', 2020),
       (162, 'Yorick', 'Male', 'Top', 'Human, Magically Altered', 'Mana', 'Melee', 'Shadow Isles', 2011),
       (163, 'Yunara', 'Female', 'Bottom', 'Human, Spiritualist', 'Mana', 'Ranged', 'Ionia', 2025),
       (164, 'Yuumi', 'Female', 'Support', 'Cat, Magically Altered', 'Mana', 'Ranged', 'Bandle City', 2019),
       (165, 'Zaahen', 'Male', 'Top', 'Darkin, Human', 'Mana', 'Melee', 'Ionia, Shurima', 2025),
       (166, 'Zac', 'Male', 'Jungle', 'Golem', 'Health costs', 'Melee', 'Zaun', 2013),
       (167, 'Zed', 'Male', 'Jungle, Middle', 'Human, Magically Altered', 'Energy', 'Melee', 'Ionia', 2012),
       (168, 'Zeri', 'Female', 'Bottom', 'Human, Magicborn', 'Mana', 'Ranged', 'Zaun', 2022),
       (169, 'Ziggs', 'Male', 'Bottom, Middle', 'Yordle', 'Mana', 'Ranged', 'Zaun', 2012),
       (170, 'Zilean', 'Male', 'Support', 'Human Magicborn', 'Mana', 'Ranged', 'Icathia, Runeterra, Shurima', 2009),
       (171, 'Zoe', 'Female', 'Middle', 'Aspect Human', 'Mana', 'Ranged', 'Targon', 2017),
       (172, 'Zyra', 'Female', 'Support', 'Human, Plant', 'Mana', 'Ranged', 'Ixtal', 2012)

ON CONFLICT (id)
    DO NOTHING;