CREATE TABLE IF NOT EXISTS champion
(
    id           INTEGER PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    gender       VARCHAR(20),
    position     VARCHAR(50),
    species      VARCHAR(100),
    resource     VARCHAR(50),
    range_type   VARCHAR(20),
    region       VARCHAR(100),
    release_year INTEGER
);

INSERT INTO champion (id, name, gender, position, species, resource, range_type, region, release_year)
VALUES (1, 'Aatrox', 'Male', 'Top', 'Darkin', 'Manaless', 'Melee', 'Runeterra, Shurima', 2013),
       (2, 'Ahri', 'Female', 'Middle', 'Vastayan', 'Mana', 'Ranged', 'Ionia', 2011),
       (3, 'Akali', 'Female', 'Middle', 'Human', 'Energy', 'Melee', 'Ionia', 2010),
       (4, 'Akshan', 'Male', 'Middle', 'Human', 'Mana', 'Ranged', 'Shurima', 2021),
       (5, 'Alistar', 'Male', 'Support', 'Minotaur', 'Mana', 'Melee', 'Noxus, Runeterra', 2009),
       (6, 'Amumu', 'Male', 'Jungle', 'Undead, Yordle', 'Mana', 'Melee', 'Shurima', 2009),
       (7, 'Ambessa', 'Female', 'Top', 'Human', 'Energy', 'Melee', 'Noxus, Piltover', 2024),
       (8, 'Anivia', 'Female', 'Middle', 'God, Spirit', 'Mana', 'Ranged', 'Freljord', 2009),
       (9, 'Annie', 'Female', 'Middle', 'Human, Magicborn', 'Mana', 'Ranged', 'Noxus, Runeterra', 2009),
       (10, 'Aphelios', 'Male', 'Bottom', 'Human, Spiritualist', 'Mana', 'Ranged', 'Targon', 2019),
       (11, 'Ashe', 'Female', 'Bottom', 'Human, Iceborn', 'Mana', 'Ranged', 'Freljord', 2009),
       (12, 'Aurelion Sol', 'Male', 'Middle', 'Celestial, Dragon', 'Mana', 'Ranged', 'Runeterra, Targon', 2016),
       (13, 'Aurora', 'Female', 'Middle', 'Vastayan', 'Mana', 'Ranged', 'Freljord', 2024),
       (14, 'Bard', 'Male', 'Support', 'Celestial', 'Mana', 'Ranged', 'Runeterra', 2015),
       (15, 'BelVeth', 'Female', 'Jungle', 'Void-Being', 'Manaless', 'Melee', 'Void', 2022),
       (16, 'Blitzcrank', 'Other', 'Support', 'Golem', 'Mana', 'Melee', 'Zaun', 2009),
       (17, 'Brand', 'Male', 'Support', 'Human, Magically Altered', 'Mana', 'Ranged', 'Freljord, Runeterra', 2011),
       (18, 'Braum', 'Male', 'Support', 'Human, Iceborn', 'Mana', 'Melee', 'Frejord', 2014),
       (19, 'Briar', 'Female', 'Jungle', 'Golem', 'Health costs', 'Melee', 'Noxus', 2023),
       (20, 'Caitlyn', 'Female', 'Bottom', 'Human', 'Mana', 'Ranged', 'Piltover', 2011),
       (21, 'Camille', 'Female', 'Top', 'Cyborg, Human', 'Mana', 'Melee', 'Piltover', 2016),
       (22, 'Cassiopea', 'Female', 'Middle, Top', 'Human, Magically Altered', 'Mana', 'Ranged', 'Noxus, Shurima', 2010),
       (23, 'Chogath', 'Male', 'Top', 'Void-Being', 'Mana', 'Melee', 'Void', 2009),
       (24, 'Corki', 'Male', 'Bottom', 'Yordle', 'Mana', 'Ranged', 'Bandle City, Piltover', 2009),
       (25, 'Darius', 'Male', 'Top', 'Human', 'Mana', 'Melee', 'Noxus', 2012),
       (26, 'Diana', 'Female', 'Jungle, Middle', 'Aspect, Human', 'Mana', 'Melee', 'Targon', 2012),
       (27, 'Dr. Mundo', 'Male', 'Jungle, Top', 'Chemically Altered, Human', 'Health costs', 'Melee', 'Zaun', 2009),
       (28, 'Ekko', 'Male', 'Jungle, Middle,', 'Human', 'Mana', 'Melee', 'Zaun', 2015),
       (29, 'Elise', 'Female', 'Jungle, Support', 'Human, Magically Altered', 'Mana', 'Melee, Ranged',
        'Noxus, Shadow Isles', 2012),
       (30, 'Evelynn', 'Female', 'Jungle', 'Deamon, Spirit', 'Mana', 'Melee', 'Runeterra', 2009),
       (31, 'Ezrael', 'Male', 'Bottom', 'Human, Magicborn', 'Mana', 'Ranged', 'Piltover', 2010),
       (32, 'Fiddlesticks', 'Other', 'Jungle', 'Demon, Spirit', 'Mana', 'Ranged', 'Runeterra', 2009),
       (33, 'Fiora', 'Female', 'Top', 'Human', 'Mana', 'Melee', 'Demacia', 2012),
       (34, 'Fizz', 'Male', 'Middle', 'Yordle', 'Mana', 'Melee', 'Bilgewater', 2011),
       (35, 'Miss Fortune', 'Female', 'Bottom', 'Human', 'Mana', 'Ranged', 'Bilgewater', 2010),
       (36, 'Twisted Fate', 'Male', 'Middle', ' Human, Magicborn', 'Mana', 'Ranged', 'Bilgewater', 2009),
       (37, 'Galio', 'Male', 'Middle', 'Golem', 'Mana', 'Melee', 'Demacia', 2010),
       (38, 'Gangplank', 'Male', 'Top', 'Human', 'Mana', 'Melee', 'Bilgewater', 2009),
       (39, 'Garen', 'Male', 'Top', 'Human', 'Manaless', 'Melee', 'Demacia', 2010),
       (40, 'Gnar', 'Male', 'Top', 'Yordle', 'Rage', 'Melee, Ranged', 'Freljord', 2014),
       (41, 'Gragas', 'Male', 'Jungle, Top', 'Human, Iceborn', 'Mana', 'Melee', 'Freljord', 2010),
       (42, 'Graves', 'Male', 'Jungle', 'Human', 'Mana', 'Ranged', 'Bilgewater', 2011),
       (43, 'Gwen', 'Female', 'Jungle, Top', 'Human, Magically Altered', 'Mana', 'Melee', 'Camavor, Shadow Isles',
        2021),
       (44, 'Renata Glasc', 'Female', 'Support', 'Chemically Altered Human', 'Mana', 'Ranged', 'Zaun', 2022),
       (45, 'Hecarim', 'Male', 'Jungle', 'Undead', 'Mana', 'Melee', 'Camavor, Shadow Isles', 2012),
       (46, 'Heimerdinger', 'Male', 'Middle, Top', 'Yordle', 'Mana', 'Rnaged', 'Piltover', 2009),
       (47, 'Hwei', 'Male', 'Middle', 'Human, Magicborn', 'Mana', 'Ranged', 'Ionia', 2023),
       (48, 'Ilaoi', 'Female', 'Top', 'Human, Spiritualist', 'Mana', 'Melee', 'Ionia', 2010),
       (49, 'Irelia', 'Female', 'Human, Spiritualist', 'Mana', 'Mana', 'Melee', 'Ionia', 2010),
       (50, 'Ivern', 'Male', 'Jungle', 'Human, Magically Altered', 'Mana', 'Ranged', 'Freljord, Ionia', 2016),
       (51, 'Janna', 'Female', 'Support', 'God, Spririt', 'Mana', 'Ranged', 'Shurima, Zaun', 2009),
       (52, 'Jarvan', 'Male', 'Jungle', 'Human', 'Mana', 'Melee', 'Demacia', 2011),
       (53, 'Jax', 'Male', 'Jungle, Top', 'Unknown', 'Mana', 'Melee', 'Icathia, Runeterra, Shurima', 2009),
       (54, 'Jayce', 'Male', 'Jungle, Top', ' Human', 'Mana', 'Melee, Ranged', 'Piltover', 2012),
       (55, 'Jhin', 'Male', 'Bottom', 'Human, Spiritualist', 'Mana', 'Ranged', 'Ionia', 2016),
       (56, 'Jinx', 'Female', 'Bottom', 'Chemically Altered, Human', 'Mana', 'Ranged', 'Zaun', 2013),
       (57, 'Ksante', 'Male', 'Top', 'Human', 'Mana', 'Melee', 'Shurima', 2022),
       (58, 'Kaisa', 'Female', 'Bottom', 'Human, Void-Being', 'Mana', 'Ranged', 'Shurima, Void', 2018),
       (59, 'Kalista', 'Female', 'Bottom', 'Undead', 'Mana', 'Ranged', 'Camover, Shadow Isles', 2014),
       (60, 'Karma', 'Female', 'Support', 'Human, Spiritualist', 'Mana', 'Ranged', 'Ionia', 2011),
       (61, 'Karthus', 'Male', 'Jungle', 'Undead', 'Mana', 'Ranged', 'Noxus, Shadow Isles', 2009),
       (62, 'Kassadin', 'Male', 'Middle', 'Human, Void-Being', 'Mana', 'Melee', 'Shurima, Void', 2009),
       (63, 'Katharina', 'Female', 'Middle', 'Human', 'Manaless', 'Melee', 'Noxus', 2009),
       (64, 'Kayle', 'Female', 'Top', 'Aspect, Human, Magically Altered', 'Mana', 'Melee, Ranged', 'Demacia, Targon',
        2009),
       (65, 'Kayn', 'Male', 'Jungle', 'Darkin, Human, Magically Altered', 'Mana', 'Melee',
        'Ionia, Noxus, Runeterra, Shurima', 2017),
       (66, 'Kennen', 'Male', 'Middle, Top', 'Yordle', 'Energy', 'Ranged', 'Ionia', 2010),
       (67, 'Khazix', 'Male', 'Jungle', 'Void-Being', 'Mana', 'Melee', 'Void', 2012),
       (68, 'Kindred', 'Other', 'Jungle', 'Void-Being', 'Mana', 'Ranged', 'Runeterra', 2015),
       (69, 'Kled', 'Male', 'Top', 'Yordle', 'Courage', 'Melee', 'Noxus', 2016),
       (70, 'Kogmaw', 'Male', 'Bottom', 'Void-Being', 'Mana', 'Ranged', 'Void', 2015),
       (71, 'Tahm Kench', 'Male', 'Support, Top', 'Demon, Spirit', 'Mana', 'Melee', 'Bilgewater, Runeterra', 2015),
       (72, 'LeBlanc', 'Female', 'Middle', 'Human, Magically Altered', 'Mana', 'Ranged', 'Noxus', 2010),
       (73, 'Lee Sin', 'Male', 'Jungle', 'Human, Spiritualist', 'Energy', 'Melee', 'Ionia', 2011),
       (74, 'Leona', 'Female', 'Support', 'Aspect, Human', 'Mana', 'Melee', 'Targon', 2011),
       (75, 'Lillia', 'Female', 'Jungle', 'Spirit ', 'Mana', 'Melee', 'Ionia', 2020),
       (76, 'Lissandra', 'Female', 'Middle', 'Human, Iceborn', 'Mana', 'Ranged', 'Freljord', 2013),
       (77, 'Lucian', 'Male', 'Bottom', 'Human', 'Mana', 'Ranged', 'Demacia, Shadow Isles', 2013),
       (78, 'Lulu', 'Female', 'Support', 'Yordle', 'Mana', 'Ranged', 'Bandle City', 2012),
       (79, 'Lux', 'Female', 'Middle, Support', 'Human, Magicborn', 'Mana', 'Ranged', 'Demacia', 2010),
       (80, 'Malphite', 'Male', 'Top', 'Golem', 'Mana', 'Melee', 'Ixtal, Shurima', 2009),
       (81, 'Malzahr', 'Middle', 'Human, Void-Being', 'Mana', 'Ranged', 'Ranged', 'Shurima, Void', 2010),
       (82, 'Maokai', 'Male', 'Support', 'Spirit', 'Mana', 'Melee', 'Shadow Isles', 2011),
       (83, 'Master Yi', 'Male', 'Jungle', 'Human, Spiritualist', 'Mana', 'Melee', 'Ionia', 2009),
       (84, 'Mel', 'Female', 'Middle', 'Human, Magically Altered', 'Mana', 'Ranged', 'Noxus, Piltover', 2025),
       (85, 'Milio', 'Male', 'Support', 'Human, Magicborn', 'Mana', 'Ranged', 'Ixtal', 2023),
       (86, 'Mordekaiser', 'Male', 'Top', 'Revenant', 'Shield', 'Melee', 'Noxus, Shadow Isles', 2010),
       (87, 'Morgana', 'Female', 'Middle, Support', 'Aspect, Human, Magically Altered', 'Mana', 'Ranged',
        'Demacia, Targon', 2009),
       (88, 'Naafri', 'Female', 'Jungle, Middle', 'Darkin, Dog', 'Mana', 'Melee', 'Shurima', 2023),
       (89, 'Nami', 'Female', 'Support', 'Vastayan', 'Mana', 'Ranged', 'Bilgewater, Runeterra', 2012),
       (90, 'Nasus', 'Male', 'Top', 'God-Warrior', 'Mana', 'Melee', 'Shurima', 2009),
       (91, 'Nautilus', 'Male', 'Support', 'Revenant', 'Mana', 'Melee', 'Bilgewater', 2012),
       (92, 'Neeko', 'Female', 'Support', 'Vastayan', 'Mana', 'Ranged', 'Ixtal', 2018),
       (93, 'Nidalee', 'Female', 'Jungle', 'Human, Spiritualist', 'Mana', 'Melee, Ranged', 'Ixtal', 2009),
       (94, 'Nilah', 'Female', 'Bottom', 'Human, Magically Altered', 'Mana', 'Melee', 'Bilgewater', 2022),
       (95, 'Nocturne', 'Male', 'Jungle', 'Demon, Spirit', 'Mana', 'Melee', 'Runeterra', 2011),
       (96, 'Nunu & Willump', 'Male', 'Jungle', 'Human, Yeti', 'Mana', 'Melee', 'Freljord', 2009),
       (97, 'Olaf', 'Male', 'Top', 'Human, Iceborn', 'Mana', 'Melee', 'Freljord', 2010),
       (98, 'Orianna', 'Female', 'Middle', 'Golem', 'Mana', 'Ranged', 'Piltover', 2011),
       (99, 'Ornn', 'Male', 'Top', 'God, Spirit', 'Mana', 'Melee', 'Freljord', 2017),
       (100, 'Pantheon', 'Male', 'Jungle, Support, Top', 'Aspect, Human', 'Mana', 'Melee', 'Targon', 2010),
       (101, 'Poppy', 'Female', 'Support, Top', 'Yordle', 'Mana', 'Melee', 'Demacia', 2010),
       (102, 'Pyke', 'Male', 'Support', 'Revenant', 'Mana', 'Melee', 'Bilgewater', 2018),
       (103,'Qijana', 'Female', 'Jungle, Middle', 'Human, Magicborn', 'Mana', 'Melee', 'Ixtal', 2019),
       (104,'Quinn', 'Female', 'Top', 'Human', 'Mana', 'Ranged', 'Demacia', 2013),
       (105,'Rakan', 'Male', 'Support', 'Vastayan', 'Mana', 'Melee', 'Ionia', 2017),
       (106,'Rammus', 'Male', 'Jungle', 'Unknown', 'Mana', 'Melee', 'Shurima', 2009),
       (107,'Reksai', 'Female', 'Jungle', 'Void-Being', 'Rage', 'Melee', 'Shurima, Void', 2014),
       (108,'Rell', 'Female', 'Support', 'Human, Magically Altered, Magicborn', 'Mana', 'Melee', 'Noxus', 2020),
       (109,'Renekton', 'Male', 'Top', 'God-Warrior', 'Fury', 'Melee', 'Shurima', 2011),
       (110,'Rengar', 'Male', 'Jungle', 'Vastayan', 'Ferocity', 'Melee', 'Ixtal, Shurima', 2012),
       (111,'Riven', 'Female', 'Top', 'Human', 'Manaless', 'Melee', 'Ionia, Noxus',2011),
       (112,'Rumble', 'Male', 'Top', 'Yordle', 'Heat', 'Melee', 'Bandle City', 2011),
       (113,'Ryze', 'Male', 'Middle', 'Human, Magically Altered', 'Mana', 'Ranged', 'Runeterra',2009)
ON CONFLICT (id)
    DO NOTHING