CREATE TABLE IF NOT EXISTS champion
(
    id           INTEGER PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    gender       VARCHAR(20),
    position     VARCHAR(50),
    species      VARCHAR(100),
    resource     VARCHAR(50),
    range_type   VARCHAR(20),
    region       VARCHAR(100),
    release_year INTEGER
);

INSERT INTO champion (id, name, gender, position, species, resource, range_type, region, release_year)
VALUES (1, 'Aatrox', 'Male', 'Top', 'Darkin', 'Manaless', 'Melee', 'Runeterra, Shurima', 2013),
       (2, 'Ahri', 'Female', 'Middle', 'Vastayan', 'Mana', 'Ranged', 'Ionia', 2011),
       (3, 'Akali', 'Female', 'Middle', 'Human', 'Energy', 'Melee', 'Ionia', 2010),
       (4, 'Akshan', 'Male', 'Middle', 'Human', 'Mana', 'Ranged', 'Shurima', 2021),
       (5, 'Alistar', 'Male', 'Support', 'Minotaur', 'Mana', 'Melee', 'Noxus, Runeterra', 2009),
       (6, 'Amumu', 'Male', 'Jungle', 'Undead, Yordle', 'Mana', 'Melee', 'Shurima', 2009),
       (7, 'Ambessa', 'Female', 'Top', 'Human', 'Energy', 'Melee', 'Noxus, Piltover', 2024),
       (8, 'Anivia', 'Female', 'Middle', 'God, Spirit', 'Mana', 'Ranged', 'Freljord', 2009),
       (9, 'Annie', 'Female', 'Middle', 'Human, Magicborn', 'Mana', 'Ranged', 'Noxus, Runeterra', 2009),
       (10, 'Aphelios', 'Male', 'Bottom', 'Human, Spiritualist', 'Mana', 'Ranged', 'Targon', 2019),
       (11, 'Ashe', 'Female', 'Bottom', 'Human, Iceborn', 'Mana', 'Ranged', 'Freljord', 2009),
       (12, 'Aurelion Sol', 'Male', 'Middle', 'Celestial, Dragon', 'Mana', 'Ranged', 'Runeterra, Targon', 2016),
       (13, 'Aurora', 'Female', 'Middle', 'Vastayan', 'Mana', 'Ranged', 'Freljord', 2024),
       (14, 'Bard', 'Male', 'Support', 'Celestial', 'Mana', 'Ranged', 'Runeterra', 2015),
       (15, 'BelVeth', 'Female', 'Jungle', 'Void-Being', 'Manaless', 'Melee', 'Void', 2022),
       (16, 'Blitzcrank', 'Other', 'Support', 'Golem', 'Mana', 'Melee', 'Zaun', 2009),
       (17, 'Brand', 'Male', 'Support', 'Human, Magically Altered', 'Mana', 'Ranged', 'Freljord, Runeterra', 2011),
       (18, 'Braum', 'Male', 'Support', 'Human, Iceborn', 'Mana', 'Melee', 'Frejord', 2014),
       (19, 'Briar', 'Female', 'Jungle', 'Golem', 'Health costs', 'Melee', 'Noxus', 2023),
       (20, 'Caitlyn', 'Female', 'Bottom', 'Human', 'Mana', 'Ranged', 'Piltover', 2011),
       (21, 'Camille', 'Female', 'Top', 'Cyborg, Human', 'Mana', 'Melee', 'Piltover', 2016),
       (22, 'Cassiopea', 'Female', 'Middle, Top', 'Human, Magically Altered', 'Mana', 'Ranged', 'Noxus, Shurima', 2010),
       (23, 'Chogath', 'Male', 'Top', 'Void-Being', 'Mana', 'Melee', 'Void', 2009),
       (24, 'Corki', 'Male', 'Bottom', 'Yordle', 'Mana', 'Ranged', 'Bandle City, Piltover', 2009),
       (25, 'Darius', 'Male', 'Top', 'Human', 'Mana', 'Melee', 'Noxus', 2012),
       (26, 'Diana', 'Female', 'Jungle, Middle', 'Aspect, Human', 'Mana', 'Melee', 'Targon', 2012),
       (27, 'Dr. Mundo', 'Male', 'Jungle, Top', 'Chemically Altered, Human', 'Health costs', 'Melee', 'Zaun', 2009),
       (28, 'Ekko', 'Male', 'Jungle, Middle,', 'Human', 'Mana', 'Melee', 'Zaun', 2015),
       (29, 'Elise', 'Female', 'Jungle, Support', 'Human, Magically Altered', 'Mana', 'Melee, Ranged',
        'Noxus, Shadow Isles', 2012),
       (30, 'Evelynn', 'Female', 'Jungle', 'Deamon, Spirit', 'Mana', 'Melee', 'Runeterra', 2009),
       (31, 'Ezrael', 'Male', 'Bottom', 'Human, Magicborn', 'Mana', 'Ranged', 'Piltover', 2010),
       (32, 'Fiddlesticks', 'Other', 'Jungle', 'Demon, Spirit', 'Mana', 'Ranged', 'Runeterra', 2009),
       (33, 'Fiora', 'Female', 'Top', 'Human', 'Mana', 'Melee', 'Demacia', 2012),
       (34, 'Fizz', 'Male', 'Middle', 'Yordle', 'Mana', 'Melee', 'Bilgewater', 2011),
       (35, 'Miss Fortune', 'Female', 'Bottom', 'Human', 'Mana', 'Ranged', 'Bilgewater', 2010),
       (36, 'Twisted Fate', 'Male', 'Middle', ' Human, Magicborn', 'Mana', 'Ranged', 'Bilgewater', 2009),
       (37, 'Galio', 'Male', 'Middle', 'Golem', 'Mana', 'Melee', 'Demacia', 2010),
       (38, 'Gangplank', 'Male', 'Top', 'Human', 'Mana', 'Melee', 'Bilgewater', 2009),
       (39, 'Garen', 'Male', 'Top', 'Human', 'Manaless', 'Melee', 'Demacia', 2010),
       (40, 'Gnar', 'Male', 'Top', 'Yordle', 'Rage', 'Melee, Ranged', 'Freljord', 2014),
       (41, 'Gragas', 'Male', 'Jungle, Top', 'Human, Iceborn', 'Mana', 'Melee', 'Freljord', 2010),
       (42, 'Graves', 'Male', 'Jungle', 'Human', 'Mana', 'Ranged', 'Bilgewater', 2011),
       (43, 'Gwen', 'Female', 'Jungle, Top', 'Human, Magically Altered', 'Mana', 'Melee', 'Camavor, Shadow Isles',
        2021),
       (44, 'Renata Glasc', 'Female', 'Support', 'Chemically Altered Human', 'Mana', 'Ranged', 'Zaun', 2022),
       (45, 'Hecarim', 'Male', 'Jungle', 'Undead', 'Mana', 'Melee', 'Camavor, Shadow Isles', 2012),
       (46, 'Heimerdinger', 'Male', 'Middle, Top', 'Yordle', 'Mana', 'Rnaged', 'Piltover', 2009),
       (47, 'Hwei', 'Male', 'Middle', 'Human, Magicborn', 'Mana', 'Ranged', 'Ionia', 2023),
       (48, 'Ilaoi', 'Female', 'Top', 'Human, Spiritualist', 'Mana', 'Melee', 'Ionia', 2010),
       (49, 'Irelia', 'Female', 'Human, Spiritualist', 'Mana', 'Mana', 'Melee', 'Ionia', 2010),
       (50, 'Ivern', 'Male', 'Jungle', 'Human, Magically Altered', 'Mana', 'Ranged', 'Freljord, Ionia', 2016),
       (51, 'Janna', 'Female', 'Support', 'God, Spririt', 'Mana', 'Ranged', 'Shurima, Zaun', 2009),
       (52, 'Jarvan', 'Male', 'Jungle', 'Human', 'Mana', 'Melee', 'Demacia', 2011),
       (53, 'Jax', 'Male', 'Jungle, Top', 'Unknown', 'Mana', 'Melee', 'Icathia, Runeterra, Shurima', 2009),
       (54, 'Jayce', 'Male', 'Jungle, Top', ' Human', 'Mana', 'Melee, Ranged', 'Piltover', 2012),
       (55, 'Jhin', 'Male', 'Bottom', 'Human, Spiritualist', 'Mana', 'Ranged', 'Ionia', 2016),
       (56, 'Jinx', 'Female', 'Bottom', 'Chemically Altered, Human', 'Mana', 'Ranged', 'Zaun', 2013)
ON CONFLICT (id)
    DO NOTHING;